config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :payment_types
  resources :users
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id, price: product.price )
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :cart
  belongs_to :order, optional: true

  def total_price
    price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord

  validates :name, :address, :email, presence: true
  validate :valid_payment_type?, on: :create
  belongs_to :payment_type, optional: true
  has_many :line_items, dependent: :destroy

  def add_line_items_from(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  private

  def valid_payment_type?
    if PaymentType.find(payment_type_id).nil?
      errors.add(:base, 'Payment type not valid')
    end
  end
end

app/models/payment_type.rb
class PaymentType < ApplicationRecord
  validates :kind, uniqueness: true, presence: true
  has_many :orders, dependent: :destroy

  def to_str
    kind
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :description, :image_url, presence: true
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
      with: %r{\.(gif|jpg|png)\Z}i,
      message: 'must be a URL for GIF, JPG or PNG image.'
  }
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  has_many :orders, through: :line_items

  private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw abort
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains
  
  class Error < StandardError
  end
  
  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise Error, "Can't delete last user"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
#---
# Excerpted from "Agile Web Development with Rails 5.1",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/rails51 for more book information.
#---
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:create, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_url,
                                notice: 'Your cart is currently empty' }
      format.js
      format.json { head :no_content }
    end
  end

  # ...
  private
  # ...

  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.fetch(:cart, {})
  end
  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to store_index_url, notice: 'Invalid cart'
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include CurrentCart
  before_action :set_cart
  skip_before_action :authorize

  def index
    @products = Product.order(:title)

    if session[:counter].nil?
      session[:counter] = 0
    end
    session[:counter] += 1
    @counter = session[:counter]

    if params[:set_locale]
      redirect_to store_index_url(locale: params[:set_locale])
    else
      @products = Product.order(:title)
    end

  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_if(condition, record)
    if condition
      render record
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/react_helper.rb
module ReactHelper
  def react_component(name, props = {})
    content_tag(:div, '', data: {react_component: {name: name, props: props}})
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
<p>
  It's <%= Time.now %>.
  We have <%= pluralize(@total_orders, "order") %>.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prapprog Books Online Store</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application' %>
  <script type="text/javascript">
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale = "<%= I18n.locale %>";
  </script>
</head>

<body>
<header class="main">
  <aside>
    <%= form_tag store_index_path, class: 'locale' do %>
      <%= select_tag 'set_locale',
                     options_for_select(LANGUAGES, I18n.locale.to_s),
                     onchange: 'this.form.submit()' %>
      <%= submit_tag 'submit', id: "submit_locale_change" %>
    <% end %> </aside>
  <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
  <h1><%= @page_title %></h1>
</header>
<section class="content">
  <nav class="side_nav">
    <div id="cart" class="carts">
      <%= render_if @cart && @cart.line_items.any?, @cart %>
    </div>
    <span style="color: #ffffff"><%= Time.now %></span>
    <span style="color: #ffffff">Visitas: <%= !@counter.nil? && @counter > 5 ? @counter : " " %></span>
    <ul>
      <li><a href="/"><%= t('.home') %></a></li>
      <li><a href="/questions"><%= t('.questions') %></a></li>
      <li><a href="/news"><%= t('.news') %></a></li>
      <li><a href="/contact"><%= t('.contact') %></a></li>
    </ul>
    <% if session[:user_id] %>
      <nav class="logged_in_nav">
        <ul>
          <li><%= link_to 'Orders', orders_path %></li>
          <li><%= link_to 'Product', products_path %> </li>
          <li><%= link_to 'Users', users_path %> </li>
          <li><%= button_to 'Logout', logout_path, method: :delete %> </li>
        </ul>
      </nav>
    <% end %>
  </nav>
  <main class='<%= controller.controller_name %>'>
    <%= yield %>
  </main>
</section>
</body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>